/**
 * -----------------------------------------------------------------------------
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
 *
 * Generated by:
 *   pnpm media:catalog   (from app/shared/media/manifest.json)
 *
 * Any manual changes will be overwritten the next time the catalog is generated.
 * Regenerate after `pnpm media:scan --write`. Treat this file as build output,
 * not handwritten source.
 *
 * The filesystem-authoritative media layer: owns galleries, image hierarchy,
 * dimensions and storage paths; carries no business copy.
 * -----------------------------------------------------------------------------
 */
import type { MediaAsset } from '~/shared/media/types'

export type ProjectMediaId =
  | 'cai-tao-nha-quan-8'
  | 'codi-boutique-hotel'
  | 'codi-villa-phan-thiet'
  | 'khach-san-eo-gio'
  | 'nha-anh-nam'
  | 'nha-ta-dung'
  | 'nha-vuon-chily'
  | 'nha-xuong-anh-cuong'
  | 'phong-giam-doc'
  | 'phong-hop-quan-7'
  | 'van-phong-quan-4'

export type ProjectMedia = {
  readonly id: ProjectMediaId
  readonly cover: MediaAsset
  readonly images: readonly MediaAsset[]
  readonly galleries: Readonly<Record<string, readonly MediaAsset[]>>
}

export const projectMedia = {
  'cai-tao-nha-quan-8': {
    id: 'cai-tao-nha-quan-8',
    cover: { path: 'projects/cai-tao-nha-quan-8/3.webp', width: 2560, height: 1707 },
    images: [
      { path: 'projects/cai-tao-nha-quan-8/3.webp', width: 2560, height: 1707 },
      { path: 'projects/cai-tao-nha-quan-8/5.webp', width: 2133, height: 2560 },
      { path: 'projects/cai-tao-nha-quan-8/12.webp', width: 2560, height: 1707 },
      { path: 'projects/cai-tao-nha-quan-8/13.webp', width: 2560, height: 1707 },
      { path: 'projects/cai-tao-nha-quan-8/14.webp', width: 2560, height: 1707 }
    ],
    galleries: {}
  },
  'codi-boutique-hotel': {
    id: 'codi-boutique-hotel',
    cover: { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-03.webp', width: 2500, height: 1507 },
    images: [
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-03.webp', width: 2500, height: 1507 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-04.webp', width: 2500, height: 1563 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-05.webp', width: 2500, height: 1563 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-06.webp', width: 2000, height: 2500 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-07.webp', width: 2000, height: 2000 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-08.webp', width: 1000, height: 1200 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-01.webp', width: 2500, height: 1667 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-02.webp', width: 2500, height: 1667 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-03.webp', width: 2500, height: 1667 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-04.webp', width: 2500, height: 1667 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-05.webp', width: 2000, height: 2400 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-06.webp', width: 2000, height: 2400 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-3/1.webp', width: 2500, height: 1800 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-3/2.webp', width: 2000, height: 2500 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-3/5.webp', width: 2000, height: 2500 },
      { path: 'projects/codi-boutique-hotel/phong-dien-hinh-3/6.webp', width: 1000, height: 1360 },
      { path: 'projects/codi-boutique-hotel/sanh-don/1.webp', width: 2500, height: 1500 },
      { path: 'projects/codi-boutique-hotel/sanh-don/2.webp', width: 2500, height: 1600 },
      { path: 'projects/codi-boutique-hotel/sanh-don/3.webp', width: 2000, height: 2500 },
      { path: 'projects/codi-boutique-hotel/sanh-don/5.webp', width: 2500, height: 1600 }
    ],
    galleries: {
        'phong-dien-hinh-1': [
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-03.webp', width: 2500, height: 1507 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-04.webp', width: 2500, height: 1563 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-05.webp', width: 2500, height: 1563 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-06.webp', width: 2000, height: 2500 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-07.webp', width: 2000, height: 2000 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-1/p3-08.webp', width: 1000, height: 1200 }
        ],
        'phong-dien-hinh-2': [
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-01.webp', width: 2500, height: 1667 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-02.webp', width: 2500, height: 1667 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-03.webp', width: 2500, height: 1667 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-04.webp', width: 2500, height: 1667 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-05.webp', width: 2000, height: 2400 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-2/p8-06.webp', width: 2000, height: 2400 }
        ],
        'phong-dien-hinh-3': [
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-3/1.webp', width: 2500, height: 1800 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-3/2.webp', width: 2000, height: 2500 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-3/5.webp', width: 2000, height: 2500 },
          { path: 'projects/codi-boutique-hotel/phong-dien-hinh-3/6.webp', width: 1000, height: 1360 }
        ],
        'sanh-don': [
          { path: 'projects/codi-boutique-hotel/sanh-don/1.webp', width: 2500, height: 1500 },
          { path: 'projects/codi-boutique-hotel/sanh-don/2.webp', width: 2500, height: 1600 },
          { path: 'projects/codi-boutique-hotel/sanh-don/3.webp', width: 2000, height: 2500 },
          { path: 'projects/codi-boutique-hotel/sanh-don/5.webp', width: 2500, height: 1600 }
        ]
      }
  },
  'codi-villa-phan-thiet': {
    id: 'codi-villa-phan-thiet',
    cover: { path: 'projects/codi-villa-phan-thiet/1.webp', width: 2560, height: 1636 },
    images: [
      { path: 'projects/codi-villa-phan-thiet/1.webp', width: 2560, height: 1636 },
      { path: 'projects/codi-villa-phan-thiet/7.webp', width: 2047, height: 2560 },
      { path: 'projects/codi-villa-phan-thiet/8.webp', width: 2560, height: 1472 },
      { path: 'projects/codi-villa-phan-thiet/10.webp', width: 2033, height: 2500 },
      { path: 'projects/codi-villa-phan-thiet/11.webp', width: 2059, height: 2500 },
      { path: 'projects/codi-villa-phan-thiet/12.webp', width: 2134, height: 2000 },
      { path: 'projects/codi-villa-phan-thiet/14.webp', width: 2560, height: 1660 },
      { path: 'projects/codi-villa-phan-thiet/15.webp', width: 2500, height: 1893 },
      { path: 'projects/codi-villa-phan-thiet/17.webp', width: 1864, height: 2560 },
      { path: 'projects/codi-villa-phan-thiet/21.webp', width: 2560, height: 1735 },
      { path: 'projects/codi-villa-phan-thiet/22.webp', width: 2560, height: 1735 },
      { path: 'projects/codi-villa-phan-thiet/23.webp', width: 2048, height: 2560 },
      { path: 'projects/codi-villa-phan-thiet/25.webp', width: 2048, height: 2560 },
      { path: 'projects/codi-villa-phan-thiet/26.webp', width: 2560, height: 1858 },
      { path: 'projects/codi-villa-phan-thiet/27.webp', width: 2560, height: 1859 },
      { path: 'projects/codi-villa-phan-thiet/29.webp', width: 2560, height: 1968 }
    ],
    galleries: {}
  },
  'khach-san-eo-gio': {
    id: 'khach-san-eo-gio',
    cover: { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/1-2.webp', width: 2560, height: 1417 },
    images: [
      { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/1-2.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/3.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/4.webp', width: 2133, height: 2560 },
      { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/5.webp', width: 2133, height: 2560 },
      { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/9.webp', width: 2133, height: 2560 },
      { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/11.webp', width: 2560, height: 1536 },
      { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/12.webp', width: 2560, height: 1536 },
      { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/3.webp', width: 2560, height: 1600 },
      { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/4.webp', width: 2560, height: 1365 },
      { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/5.webp', width: 2560, height: 1365 },
      { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/12.webp', width: 2560, height: 2560 },
      { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/20.webp', width: 2500, height: 2500 },
      { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/22.webp', width: 2560, height: 1536 },
      { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/1.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/2.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/3.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/5.webp', width: 1969, height: 2560 },
      { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/7.webp', width: 1920, height: 2560 },
      { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/8.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/phong-don-dien-hinh/1.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/phong-don-dien-hinh/2.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/phong-don-dien-hinh/4.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/phong-studio-01/3.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/phong-studio-02/1.webp', width: 2560, height: 1600 },
      { path: 'projects/khach-san-eo-gio/phong-studio-02/2.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/phong-studio-02/3.webp', width: 2560, height: 1417 },
      { path: 'projects/khach-san-eo-gio/phong-studio-02/5.webp', width: 2560, height: 1195 },
      { path: 'projects/khach-san-eo-gio/sanh-don/14.webp', width: 2560, height: 1600 },
      { path: 'projects/khach-san-eo-gio/sanh-don/21.webp', width: 2560, height: 1600 },
      { path: 'projects/khach-san-eo-gio/sanh-don/24.webp', width: 2560, height: 1600 }
    ],
    galleries: {
        'can-ho-1-phong-ngu': [
          { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/1-2.webp', width: 2560, height: 1417 },
          { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/3.webp', width: 2560, height: 1417 },
          { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/4.webp', width: 2133, height: 2560 },
          { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/5.webp', width: 2133, height: 2560 },
          { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/9.webp', width: 2133, height: 2560 },
          { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/11.webp', width: 2560, height: 1536 },
          { path: 'projects/khach-san-eo-gio/can-ho-1-phong-ngu/12.webp', width: 2560, height: 1536 }
        ],
        'can-ho-3-phong-ngu': [
          { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/3.webp', width: 2560, height: 1600 },
          { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/4.webp', width: 2560, height: 1365 },
          { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/5.webp', width: 2560, height: 1365 },
          { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/12.webp', width: 2560, height: 2560 },
          { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/20.webp', width: 2500, height: 2500 },
          { path: 'projects/khach-san-eo-gio/can-ho-3-phong-ngu/22.webp', width: 2560, height: 1536 }
        ],
        'phong-doi-dien-hinh': [
          { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/1.webp', width: 2560, height: 1417 },
          { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/2.webp', width: 2560, height: 1417 },
          { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/3.webp', width: 2560, height: 1417 },
          { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/5.webp', width: 1969, height: 2560 },
          { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/7.webp', width: 1920, height: 2560 },
          { path: 'projects/khach-san-eo-gio/phong-doi-dien-hinh/8.webp', width: 2560, height: 1417 }
        ],
        'phong-don-dien-hinh': [
          { path: 'projects/khach-san-eo-gio/phong-don-dien-hinh/1.webp', width: 2560, height: 1417 },
          { path: 'projects/khach-san-eo-gio/phong-don-dien-hinh/2.webp', width: 2560, height: 1417 },
          { path: 'projects/khach-san-eo-gio/phong-don-dien-hinh/4.webp', width: 2560, height: 1417 }
        ],
        'phong-studio-01': [
          { path: 'projects/khach-san-eo-gio/phong-studio-01/3.webp', width: 2560, height: 1417 }
        ],
        'phong-studio-02': [
          { path: 'projects/khach-san-eo-gio/phong-studio-02/1.webp', width: 2560, height: 1600 },
          { path: 'projects/khach-san-eo-gio/phong-studio-02/2.webp', width: 2560, height: 1417 },
          { path: 'projects/khach-san-eo-gio/phong-studio-02/3.webp', width: 2560, height: 1417 },
          { path: 'projects/khach-san-eo-gio/phong-studio-02/5.webp', width: 2560, height: 1195 }
        ],
        'sanh-don': [
          { path: 'projects/khach-san-eo-gio/sanh-don/14.webp', width: 2560, height: 1600 },
          { path: 'projects/khach-san-eo-gio/sanh-don/21.webp', width: 2560, height: 1600 },
          { path: 'projects/khach-san-eo-gio/sanh-don/24.webp', width: 2560, height: 1600 }
        ]
      }
  },
  'nha-anh-nam': {
    id: 'nha-anh-nam',
    cover: { path: 'projects/nha-anh-nam/1.webp', width: 2560, height: 1600 },
    images: [
      { path: 'projects/nha-anh-nam/1.webp', width: 2560, height: 1600 },
      { path: 'projects/nha-anh-nam/2.webp', width: 2560, height: 1600 },
      { path: 'projects/nha-anh-nam/3.webp', width: 2560, height: 1600 },
      { path: 'projects/nha-anh-nam/4.webp', width: 2048, height: 2560 },
      { path: 'projects/nha-anh-nam/5.webp', width: 2560, height: 1600 },
      { path: 'projects/nha-anh-nam/7.webp', width: 2560, height: 1551 },
      { path: 'projects/nha-anh-nam/8.webp', width: 2560, height: 1600 },
      { path: 'projects/nha-anh-nam/10.webp', width: 2560, height: 1600 },
      { path: 'projects/nha-anh-nam/11.webp', width: 2560, height: 1600 }
    ],
    galleries: {}
  },
  'nha-ta-dung': {
    id: 'nha-ta-dung',
    cover: { path: 'projects/nha-ta-dung/1.webp', width: 2560, height: 1829 },
    images: [
      { path: 'projects/nha-ta-dung/1.webp', width: 2560, height: 1829 },
      { path: 'projects/nha-ta-dung/2.webp', width: 2560, height: 1829 },
      { path: 'projects/nha-ta-dung/3.webp', width: 2560, height: 1682 },
      { path: 'projects/nha-ta-dung/4.webp', width: 2560, height: 1682 },
      { path: 'projects/nha-ta-dung/5.webp', width: 2560, height: 1682 },
      { path: 'projects/nha-ta-dung/6.webp', width: 2103, height: 2560 },
      { path: 'projects/nha-ta-dung/7.webp', width: 2103, height: 2560 }
    ],
    galleries: {}
  },
  'nha-vuon-chily': {
    id: 'nha-vuon-chily',
    cover: { path: 'projects/nha-vuon-chily/1.webp', width: 2200, height: 1800 },
    images: [
      { path: 'projects/nha-vuon-chily/1.webp', width: 2200, height: 1800 },
      { path: 'projects/nha-vuon-chily/3.webp', width: 1500, height: 1800 },
      { path: 'projects/nha-vuon-chily/4.webp', width: 1500, height: 1800 },
      { path: 'projects/nha-vuon-chily/5.webp', width: 2200, height: 1672 },
      { path: 'projects/nha-vuon-chily/7.webp', width: 1600, height: 2000 },
      { path: 'projects/nha-vuon-chily/8.webp', width: 1600, height: 2000 },
      { path: 'projects/nha-vuon-chily/9.webp', width: 2000, height: 2000 },
      { path: 'projects/nha-vuon-chily/10.webp', width: 2000, height: 2000 },
      { path: 'projects/nha-vuon-chily/12.webp', width: 1800, height: 2200 },
      { path: 'projects/nha-vuon-chily/14.webp', width: 1800, height: 2200 },
      { path: 'projects/nha-vuon-chily/15.webp', width: 2000, height: 1600 },
      { path: 'projects/nha-vuon-chily/22.webp', width: 2200, height: 1700 },
      { path: 'projects/nha-vuon-chily/23.webp', width: 1760, height: 2200 },
      { path: 'projects/nha-vuon-chily/24.webp', width: 1760, height: 2200 },
      { path: 'projects/nha-vuon-chily/25.webp', width: 1660, height: 2200 },
      { path: 'projects/nha-vuon-chily/26.webp', width: 1760, height: 2200 },
      { path: 'projects/nha-vuon-chily/27.webp', width: 1600, height: 2000 },
      { path: 'projects/nha-vuon-chily/28.webp', width: 1600, height: 1838 },
      { path: 'projects/nha-vuon-chily/29.webp', width: 1600, height: 2000 },
      { path: 'projects/nha-vuon-chily/30.webp', width: 2200, height: 1700 },
      { path: 'projects/nha-vuon-chily/31.webp', width: 1600, height: 2000 },
      { path: 'projects/nha-vuon-chily/32.webp', width: 2000, height: 1600 },
      { path: 'projects/nha-vuon-chily/34.webp', width: 1600, height: 2000 },
      { path: 'projects/nha-vuon-chily/35.webp', width: 1600, height: 2000 },
      { path: 'projects/nha-vuon-chily/36.webp', width: 1600, height: 2000 },
      { path: 'projects/nha-vuon-chily/37.webp', width: 1600, height: 2000 }
    ],
    galleries: {}
  },
  'nha-xuong-anh-cuong': {
    id: 'nha-xuong-anh-cuong',
    cover: { path: 'projects/nha-xuong-anh-cuong/1.webp', width: 2560, height: 1600 },
    images: [
      { path: 'projects/nha-xuong-anh-cuong/1.webp', width: 2560, height: 1600 },
      { path: 'projects/nha-xuong-anh-cuong/2.webp', width: 2560, height: 1600 },
      { path: 'projects/nha-xuong-anh-cuong/4.webp', width: 2560, height: 942 }
    ],
    galleries: {}
  },
  'phong-giam-doc': {
    id: 'phong-giam-doc',
    cover: { path: 'projects/phong-giam-doc/1.webp', width: 1900, height: 1417 },
    images: [
      { path: 'projects/phong-giam-doc/1.webp', width: 1900, height: 1417 },
      { path: 'projects/phong-giam-doc/2.webp', width: 1900, height: 1924 },
      { path: 'projects/phong-giam-doc/3.webp', width: 1900, height: 1427 },
      { path: 'projects/phong-giam-doc/4.webp', width: 1900, height: 1425 },
      { path: 'projects/phong-giam-doc/5.webp', width: 1900, height: 2097 },
      { path: 'projects/phong-giam-doc/6.webp', width: 1900, height: 2121 },
      { path: 'projects/phong-giam-doc/7.webp', width: 1900, height: 2122 },
      { path: 'projects/phong-giam-doc/8.webp', width: 1900, height: 2125 },
      { path: 'projects/phong-giam-doc/9.webp', width: 1900, height: 2113 },
      { path: 'projects/phong-giam-doc/10.webp', width: 1831, height: 1916 }
    ],
    galleries: {}
  },
  'phong-hop-quan-7': {
    id: 'phong-hop-quan-7',
    cover: { path: 'projects/phong-hop-quan-7/p-hop1.webp', width: 1979, height: 2560 },
    images: [
      { path: 'projects/phong-hop-quan-7/p-hop1.webp', width: 1979, height: 2560 },
      { path: 'projects/phong-hop-quan-7/p-hop2.webp', width: 1979, height: 2560 },
      { path: 'projects/phong-hop-quan-7/p-hop3.webp', width: 2560, height: 1513 },
      { path: 'projects/phong-hop-quan-7/p-hop4.webp', width: 2200, height: 1300 },
      { path: 'projects/phong-hop-quan-7/pkd-1.webp', width: 2560, height: 1677 },
      { path: 'projects/phong-hop-quan-7/pkd-2.webp', width: 2560, height: 1632 },
      { path: 'projects/phong-hop-quan-7/pkd-3.webp', width: 2560, height: 2560 },
      { path: 'projects/phong-hop-quan-7/pkt1-1.webp', width: 2560, height: 1609 },
      { path: 'projects/phong-hop-quan-7/pkt1-2.webp', width: 1979, height: 2560 },
      { path: 'projects/phong-hop-quan-7/pkt1-3.webp', width: 2560, height: 1746 }
    ],
    galleries: {}
  },
  'van-phong-quan-4': {
    id: 'van-phong-quan-4',
    cover: { path: 'projects/van-phong-quan-4/1.webp', width: 2560, height: 2560 },
    images: [
      { path: 'projects/van-phong-quan-4/1.webp', width: 2560, height: 2560 },
      { path: 'projects/van-phong-quan-4/2.webp', width: 2560, height: 2560 },
      { path: 'projects/van-phong-quan-4/5.webp', width: 2560, height: 2560 },
      { path: 'projects/van-phong-quan-4/6.webp', width: 2560, height: 2560 },
      { path: 'projects/van-phong-quan-4/7.webp', width: 2560, height: 2560 },
      { path: 'projects/van-phong-quan-4/8.webp', width: 2560, height: 2560 },
      { path: 'projects/van-phong-quan-4/9.webp', width: 2560, height: 2560 },
      { path: 'projects/van-phong-quan-4/10.webp', width: 2560, height: 1920 },
      { path: 'projects/van-phong-quan-4/11.webp', width: 2286, height: 2560 }
    ],
    galleries: {}
  }
} satisfies Record<ProjectMediaId, ProjectMedia>

/** Company's own workshop gallery - powers the Nha xuong (factory) page. */
export const workshopMedia: readonly MediaAsset[] = [
  { path: 'company/workshop/1.webp', width: 1771, height: 2552 },
  { path: 'company/workshop/2.webp', width: 2560, height: 1711 },
  { path: 'company/workshop/3.webp', width: 2560, height: 1581 },
  { path: 'company/workshop/4.webp', width: 2560, height: 1541 },
  { path: 'company/workshop/5.webp', width: 2560, height: 1508 },
  { path: 'company/workshop/6.webp', width: 2560, height: 1710 },
  { path: 'company/workshop/7.webp', width: 2560, height: 1733 },
  { path: 'company/workshop/8.webp', width: 2560, height: 1711 },
  { path: 'company/workshop/9.webp', width: 2560, height: 1830 },
  { path: 'company/workshop/10.webp', width: 2560, height: 1711 },
  { path: 'company/workshop/11.webp', width: 2560, height: 1711 }
]

export const companyMedia = {
  aboutWorkspace: { path: 'company/about-workspace.webp', width: 2048, height: 2560 },
  companyStory: { path: 'company/company-story.webp', width: 900, height: 603 },
  homeMaterial01DrawingV1: { path: 'company/homepage-material-story/home-material-01-drawing-v1.webp', width: 1586, height: 992 },
  homeMaterial02MaterialV1: { path: 'company/homepage-material-story/home-material-02-material-v1.webp', width: 1586, height: 992 },
  homeMaterial03FactoryV1: { path: 'company/homepage-material-story/home-material-03-factory-v1.webp', width: 1586, height: 992 },
  homeMaterial04SpaceV1: { path: 'company/homepage-material-story/home-material-04-space-v1.webp', width: 1586, height: 992 },
  homeMaterialEoGio00ExistingV1: { path: 'company/homepage-material-story/home-material-eo-gio-00-existing-v1.webp', width: 1586, height: 992 },
  homeMaterialEoGio01DrawingV2: { path: 'company/homepage-material-story/home-material-eo-gio-01-drawing-v2.webp', width: 1586, height: 992 },
  homeMaterialEoGio02MaterialV2: { path: 'company/homepage-material-story/home-material-eo-gio-02-material-v2.webp', width: 1586, height: 992 },
  homeMaterialEoGio03FactoryV2: { path: 'company/homepage-material-story/home-material-eo-gio-03-factory-v2.webp', width: 1586, height: 992 },
  mapAddress: { path: 'company/map-address.webp', width: 1105, height: 637 }
} satisfies Record<string, MediaAsset>

export const brandMedia = {
  bannerHome: { path: 'brand/banner-home.webp', width: 2560, height: 1636 }
} satisfies Record<string, MediaAsset>
