// Generates the typed media catalog (app/media/catalog.generated.ts) from the manifest.
// The catalog is the filesystem-authoritative media layer: it owns galleries, image
// hierarchy, dimensions and storage paths. It carries NO business copy. The business
// layer references it only through stable identifiers (project folder id / named keys).
//
// Usage: pnpm media:catalog   (run after `pnpm media:scan --write`)
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { readManifest, REPO_ROOT } from './lib'
import type { MediaManifestAsset } from '../../app/shared/media/types'

const OUTPUT = join(REPO_ROOT, 'app/media/catalog.generated.ts')

const naturalCompare = (a: string, b: string): number =>
  a.localeCompare(b, 'en', { numeric: true, sensitivity: 'base' })

const camelKey = (slug: string): string =>
  slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())

const assetLiteral = (asset: MediaManifestAsset): string =>
  `{ path: '${asset.path}', width: ${asset.width ?? 0}, height: ${asset.height ?? 0} }`

const run = () => {
  const manifest = readManifest()

  const projects = manifest.assets.filter(a => a.category === 'projects')
  const workshop = manifest.assets.filter(a => a.group === 'workshop')
  const companyLoose = manifest.assets.filter(a => a.category === 'company' && a.group !== 'workshop')
  const brand = manifest.assets.filter(a => a.category === 'brand')

  // Group project assets: project id → gallery slug ('' for images directly under the project)
  const projectMap = new Map<string, Map<string, MediaManifestAsset[]>>()
  for (const asset of projects) {
    const segments = (asset.group ?? '').split('/')
    const projectId = segments[0] as string
    const gallery = segments.slice(1).join('/') // '' when the image sits directly in the project
    if (!projectMap.has(projectId)) {
      projectMap.set(projectId, new Map())
    }
    const galleries = projectMap.get(projectId) as Map<string, MediaManifestAsset[]>
    if (!galleries.has(gallery)) {
      galleries.set(gallery, [])
    }
    galleries.get(gallery)?.push(asset)
  }

  const projectIds = [...projectMap.keys()].sort(naturalCompare)

  const projectEntries = projectIds.map((projectId) => {
    const galleries = projectMap.get(projectId) as Map<string, MediaManifestAsset[]>
    const galleryNames = [...galleries.keys()].filter(name => name !== '').sort(naturalCompare)

    const allImages = [...galleries.values()]
      .flat()
      .sort((a, b) => naturalCompare(a.path, b.path))

    const galleryLiteral = galleryNames.length === 0
      ? '{}'
      : `{\n${galleryNames
        .map((name) => {
          const items = (galleries.get(name) as MediaManifestAsset[])
            .sort((a, b) => naturalCompare(a.path, b.path))
          return `        '${name}': [\n${items.map(a => `          ${assetLiteral(a)}`).join(',\n')}\n        ]`
        })
        .join(',\n')}\n      }`

    return `  '${projectId}': {
    id: '${projectId}',
    cover: ${assetLiteral(allImages[0] as MediaManifestAsset)},
    images: [
${allImages.map(a => `      ${assetLiteral(a)}`).join(',\n')}
    ],
    galleries: ${galleryLiteral}
  }`
  })

  const namedLiteral = (assets: MediaManifestAsset[]): string =>
    `{\n${assets
      .sort((a, b) => naturalCompare(a.path, b.path))
      .map((a) => {
        const key = camelKey(a.path.split('/').pop()?.replace(/\.\w+$/, '') ?? '')
        return `  ${key}: ${assetLiteral(a)}`
      })
      .join(',\n')}\n}`

  const workshopLiteral = workshop
    .sort((a, b) => naturalCompare(a.path, b.path))
    .map(a => `  ${assetLiteral(a)}`)
    .join(',\n')

  const output = `/**
 * -----------------------------------------------------------------------------
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
 *
 * Generated by:
 *   pnpm media:catalog   (from app/shared/media/manifest.json)
 *
 * Any manual changes will be overwritten the next time the catalog is generated.
 * Regenerate after \`pnpm media:scan --write\`. Treat this file as build output,
 * not handwritten source.
 *
 * The filesystem-authoritative media layer: owns galleries, image hierarchy,
 * dimensions and storage paths; carries no business copy.
 * -----------------------------------------------------------------------------
 */
import type { MediaAsset } from '~/shared/media/types'

export type ProjectMediaId =
${projectIds.map(id => `  | '${id}'`).join('\n')}

export type ProjectMedia = {
  readonly id: ProjectMediaId
  readonly cover: MediaAsset
  readonly images: readonly MediaAsset[]
  readonly galleries: Readonly<Record<string, readonly MediaAsset[]>>
}

export const projectMedia = {
${projectEntries.join(',\n')}
} satisfies Record<ProjectMediaId, ProjectMedia>

/** Company's own workshop gallery - powers the Nha xuong (factory) page. */
export const workshopMedia: readonly MediaAsset[] = [
${workshopLiteral}
]

export const companyMedia = ${namedLiteral(companyLoose)} satisfies Record<string, MediaAsset>

export const brandMedia = ${namedLiteral(brand)} satisfies Record<string, MediaAsset>
`

  writeFileSync(OUTPUT, output, 'utf8')
  console.log(`[media:catalog] wrote ${OUTPUT}`)
  console.log(`[media:catalog] ${projectIds.length} projects, ${workshop.length} workshop, ${companyLoose.length} company, ${brand.length} brand`)
}

run()
